---
sudo: false
dist: xenial

jobs:
  include:
  - language: node_js
    node_js: 10
    cache:
      directories:
      - node_modules
    before_install:
    - npm update
    install:
    - npm install
    - bundle exec jekyll build
    script:
    - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
    - npm test
    after_success:
    - npm run coveralls

  # - language: python
  #   python:
  #   - 3.6
  #   before_install:
  #   - npm update
  #   install:
  #   - npm install
  #   - bundle install
