sudo: false
addons:
  chrome:
    stable

language: python
python:
  - "3.6"
# branches:
#   only:
#   - master
#   - gh-pages
#   - _get_build_working
cache:
  bundler: true
  directories:
  - node_modules
  - /home/travis/.rvm/gems

before_install:
- nvm install node 11.10.0
- npm update

install:
- bundler install
- npm install
- pip install -r requirements_test.txt

# from https://travis-ci.community/t/how-to-setup-chromedriver-74-with-chrome-74-for-travis/2678/7
before_script:
- LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
- curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
- unzip chromedriver_linux64.zip -d ~/bin
- export PATH=$PATH:~/bin

script:
- echo path=$PATH
- bundle exec jekyll build -d _site
- bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
- npm test
- bundle exec jekyll serve --no-watch &
- sleep 5s
- python -m pytest . --driver-path ~/bin/chromedriver --use-headless

after_success:
- npm run coveralls
