sudo: false
addons:
  chrome:
    stable
  # apt:
  #   packages:
  #     - xvfb

language: python
python:
  - "3.6"      # current default Python on Travis CI
# branches:
#   only:
#   - master
#   - gh-pages
#   - _get_build_working
cache:
  bundler: true
  directories:
  - node_modules

before_install:
# - export DISPLAY=':99.0'
# - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- nvm install node 11.10.0
- npm update

install:
- bundler install
- npm install
- pip install -r test_requirements.txt

# from https://travis-ci.community/t/how-to-setup-chromedriver-74-with-chrome-74-for-travis/2678/7
before_script:
- LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
- curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
- unzip chromedriver_linux64.zip -d ~/bin

script:
# where is this getting stored??
- bundle exec which jekyll
- bundle exec jekyll build -d _site
- bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
- npm test
- bundle exec jekyll serve --no-watch &
- sleep 5s
- # start your web application and listen on `localhost` - from https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-the-chrome-addon-in-the-headless-mode
# - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:5000 &
- python -m pytest . --driver-path ~/bin/chrome-driver

after_success:
- npm run coveralls
