sudo: false
dist: xenial

jobs:
  include:
    - language: node_js
    node_js: 10
    cache:
      directories:
      - node_modules
    before_install:
    - npm update
    install:
    - npm install
    script:
    - npm test
    after_success:
    - npm run coveralls

    - language: ruby
    rvm:
      - 2.1
    install:
      - bundle exec jekyll build
    script:
      - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
